--
-- PostgreSQL database dump
--

\restrict 4nQagUj1YjnFJVZ6Z9LVSgpqbnac1gfBiSoFUyQo6N1DlpjdAX7DAYBUntvHmEi

-- Dumped from database version 15.15 (Homebrew)
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE parking_lot_db;
--
-- Name: parking_lot_db; Type: DATABASE; Schema: -; Owner: haoyu
--

CREATE DATABASE parking_lot_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.UTF-8';


ALTER DATABASE parking_lot_db OWNER TO haoyu;

\unrestrict 4nQagUj1YjnFJVZ6Z9LVSgpqbnac1gfBiSoFUyQo6N1DlpjdAX7DAYBUntvHmEi
\connect parking_lot_db
\restrict 4nQagUj1YjnFJVZ6Z9LVSgpqbnac1gfBiSoFUyQo6N1DlpjdAX7DAYBUntvHmEi

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: parking_slots; Type: TABLE; Schema: public; Owner: haoyu
--

CREATE TABLE public.parking_slots (
    id bigint NOT NULL,
    slot_number character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    version integer,
    CONSTRAINT parking_slots_status_check CHECK (((status)::text = ANY ((ARRAY['FREE'::character varying, 'OCCUPIED'::character varying, 'MAINTAIN'::character varying])::text[]))),
    CONSTRAINT parking_slots_type_check CHECK (((type)::text = ANY ((ARRAY['STANDARD'::character varying, 'VIP'::character varying, 'LARGE'::character varying])::text[])))
);


ALTER TABLE public.parking_slots OWNER TO haoyu;

--
-- Name: parking_slots_id_seq; Type: SEQUENCE; Schema: public; Owner: haoyu
--

ALTER TABLE public.parking_slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_slots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: haoyu
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    entry_time timestamp(6) without time zone NOT NULL,
    exit_time timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    total_amount numeric(10,2),
    slot_id bigint NOT NULL,
    vehicle_id bigint,
    slot_type character varying(20) NOT NULL,
    CONSTRAINT tickets_slot_type_check CHECK (((slot_type)::text = ANY ((ARRAY['STANDARD'::character varying, 'VIP'::character varying, 'LARGE'::character varying])::text[]))),
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAID'::character varying])::text[])))
);


ALTER TABLE public.tickets OWNER TO haoyu;

--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: haoyu
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle; Type: TABLE; Schema: public; Owner: haoyu
--

CREATE TABLE public.vehicle (
    id bigint NOT NULL,
    type character varying(20) NOT NULL,
    vehicle_plate character varying(255) NOT NULL,
    CONSTRAINT vehicle_type_check CHECK (((type)::text = ANY (ARRAY[('STANDARD'::character varying)::text, ('VIP'::character varying)::text, ('LARGE'::character varying)::text])))
);


ALTER TABLE public.vehicle OWNER TO haoyu;

--
-- Name: vehicle_id_seq; Type: SEQUENCE; Schema: public; Owner: haoyu
--

ALTER TABLE public.vehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: parking_slots; Type: TABLE DATA; Schema: public; Owner: haoyu
--

COPY public.parking_slots (id, slot_number, status, type, version) FROM stdin;
2	A002	MAINTAIN	VIP	0
3	A003	OCCUPIED	LARGE	0
7	A007	FREE	VIP	0
8	A008	MAINTAIN	LARGE	0
9	A009	MAINTAIN	STANDARD	0
10	A010	MAINTAIN	VIP	0
11	A011	MAINTAIN	LARGE	0
12	A012	OCCUPIED	STANDARD	0
13	A013	OCCUPIED	VIP	0
14	A014	OCCUPIED	LARGE	0
15	A015	OCCUPIED	STANDARD	0
6	A006	OCCUPIED	STANDARD	1
4	A004	FREE	VIP	2
5	A005	FREE	LARGE	6
1	A001	FREE	STANDARD	18
\.


--
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: haoyu
--

COPY public.tickets (id, entry_time, exit_time, status, total_amount, slot_id, vehicle_id, slot_type) FROM stdin;
3	2025-12-19 10:08:58.166247	2025-12-24 15:41:23.366603	PAID	1256.00	4	2	VIP
8	2025-12-25 15:50:15.021865	2025-12-25 15:51:23.513352	PAID	16.00	5	6	LARGE
5	2025-12-24 14:50:37.52243	2025-12-24 15:00:36.602268	PAID	16.00	5	6	LARGE
4	2025-12-19 10:32:09.487892	2025-12-23 14:44:25.559781	PAID	907.00	5	3	LARGE
13	2025-12-29 10:30:15.982255	2025-12-29 10:30:18.19781	PAID	16.00	1	1	STANDARD
12	2025-12-29 09:44:20.660513	2025-12-29 09:44:23.406511	PAID	16.00	1	1	STANDARD
11	2025-12-26 14:10:23.006516	2025-12-26 14:10:38.574852	PAID	16.00	1	1	STANDARD
10	2025-12-26 10:21:55.103558	2025-12-26 10:21:58.441973	PAID	16.00	1	1	STANDARD
9	2025-12-26 10:12:35.984704	2025-12-26 10:12:48.940984	PAID	16.00	1	1	STANDARD
7	2025-12-24 16:55:17.181714	2025-12-24 17:39:46.074556	PAID	16.00	1	1	STANDARD
6	2025-12-24 15:50:25.233738	2025-12-24 15:50:36.552915	PAID	16.00	1	1	STANDARD
1	2025-12-18 21:07:49.34256	2025-12-24 15:41:17.061034	PAID	1112.00	1	1	STANDARD
14	2026-01-04 11:13:58.500984	2026-01-04 11:14:02.884581	PAID	16.00	1	1	STANDARD
\.


--
-- Data for Name: vehicle; Type: TABLE DATA; Schema: public; Owner: haoyu
--

COPY public.vehicle (id, type, vehicle_plate) FROM stdin;
1	STANDARD	ABC-001
2	VIP	ABC-002
3	LARGE	ABC-003
4	STANDARD	ABC-004
5	VIP	ABC-005
6	LARGE	ABC-007
7	LARGE	ABC-008
8	LARGE	ABC-009
9	LARGE	ABC-010
10	LARGE	ABC-006
11	LARGE	ABC-011
\.


--
-- Name: parking_slots_id_seq; Type: SEQUENCE SET; Schema: public; Owner: haoyu
--

SELECT pg_catalog.setval('public.parking_slots_id_seq', 15, true);


--
-- Name: tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: haoyu
--

SELECT pg_catalog.setval('public.tickets_id_seq', 14, true);


--
-- Name: vehicle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: haoyu
--

SELECT pg_catalog.setval('public.vehicle_id_seq', 11, true);


--
-- Name: parking_slots parking_slots_pkey; Type: CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.parking_slots
    ADD CONSTRAINT parking_slots_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: parking_slots uknq6ujp1fm86yxkigslk0poscj; Type: CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.parking_slots
    ADD CONSTRAINT uknq6ujp1fm86yxkigslk0poscj UNIQUE (slot_number);


--
-- Name: vehicle ukqxr4sh5pge32pvk92oh5hfpex; Type: CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT ukqxr4sh5pge32pvk92oh5hfpex UNIQUE (vehicle_plate);


--
-- Name: vehicle vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_pkey PRIMARY KEY (id);


--
-- Name: idx_slot_status_type; Type: INDEX; Schema: public; Owner: haoyu
--

CREATE INDEX idx_slot_status_type ON public.parking_slots USING btree (status, type);


--
-- Name: idx_ticket_status_exit_time; Type: INDEX; Schema: public; Owner: haoyu
--

CREATE INDEX idx_ticket_status_exit_time ON public.tickets USING btree (status, exit_time);


--
-- Name: idx_ticket_vehicle_status; Type: INDEX; Schema: public; Owner: haoyu
--

CREATE INDEX idx_ticket_vehicle_status ON public.tickets USING btree (vehicle_id, status);


--
-- Name: tickets fkdwwiak8jaohcvbak1sv93h9h3; Type: FK CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkdwwiak8jaohcvbak1sv93h9h3 FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id);


--
-- Name: tickets fkgg7aaosvk9wih0h81shw6njas; Type: FK CONSTRAINT; Schema: public; Owner: haoyu
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkgg7aaosvk9wih0h81shw6njas FOREIGN KEY (slot_id) REFERENCES public.parking_slots(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 4nQagUj1YjnFJVZ6Z9LVSgpqbnac1gfBiSoFUyQo6N1DlpjdAX7DAYBUntvHmEi

